baseURL = "https://falcontricks.example.com/"
languageCode = "fr"
title = "FalconTricks"
theme = "blowfish"
defaultContentLanguage = "fr"
canonifyURLs = true
enableRobotsTXT = true
enableEmoji = true
summaryLength = 0

# Inclusion des autres fichiers
config = ["config.toml", "params.toml"]
