enableProfileLayout = true
colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
replyByEmail = false
disableImageOptimization = false
disableTextInHeader = true
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"
logo = "img/falcon.png"
defaultFeaturedImage = "/img/background.png"
defaultBackgroundImage = "/img/background.png"

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"
  homepageImage = "img/background.png"
  showRecent = true
  showRecentItems = 5
  showMoreLink = false
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = false

[article]
  showDate = true
  showReadingTime = true
  showTableOfContents = true
  showWordCount = false
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  showDateOnlyInArticle = false
  showDateUpdated = false
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = false
  showEdit = false
  editAppendPath = true
  seriesOpened = false
  showTaxonomies = false
  showAuthorsBadges = false
  invertPagination = false

[list]
  showHero = true
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = true
  orderByWeight = false
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false
  heroStyle = "background"


[taxonomies]
  showTermCount = true
  showHero = true
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false

[term]
  showHero = true
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false


