# netlify.toml

[build]
  # Met à jour les modules Hugo et build le site en production
  command = "git submodule update --init --recursive && hugo mod get -u && hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.16"
  TZ = "UTC"  # ou ta timezone locale

[context.production.environment]
  HUGO_VERSION = "0.147.8"  # ta version locale de Hugo
  HUGO_ENV = "production"
  GIT_SUBMODULE_STRATEGY = "recursive"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.147.8"
