# netlify.toml
# Configuration pour déployer un site Hugo (Blowfish) sur Netlify

[build]
  command = "hugo --gc --minify"      # commande pour générer le site
  publish = "public"                  # dossier généré par Hugo à publier
  # base = ""                         # laisse vide si Hugo est à la racine
  # functions = "netlify/functions"   # optionnel, pas nécessaire ici

[context.production.environment]
  HUGO_VERSION = "0.147.8"           # version de Hugo à utiliser
  HUGO_ENV = "production"            # mode production pour Hugo

